chain_id: 1
grpc_data_stream_endpoint: grpc.mainnet.aptoslabs.com:443
grpc_data_stream_api_key: aptoslabs_QgGZfNFeGps_6CZq4KDosqftsr41Cq5si6r3pZxBiDRgh
starting_version: 0
db_connection_uri: "postgresql://postgres:example@localhost:5432/example_event"
